name: Format code

on:
  pull_request:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    container:
      image: node:20

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.12.4 # or your preferred pnpm version

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Run formatter
        run: pnpm format
